const $=s=>document.querySelector(s);let category="global",items=[],prompt=null;
const titles={global:"Global headlines",international:"International headlines",national:"National headlines",state:"Maharashtra & State headlines",local:"Local headlines"};
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function toast(t){let x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2500)}
function render(){let q=$("#search").value.toLowerCase(),src=$("#source").value;let a=items.filter(x=>(src=="all"||x.source==src)&&(!q||`${x.title} ${x.description} ${x.source}`.toLowerCase().includes(q)));$("#count").textContent=a.length;$("#ticker").textContent=a.slice(0,5).map(x=>x.title).join(" • ")||"No headlines available.";
$("#newsGrid").innerHTML=a.length?a.map(x=>`<article class="card">${x.image?`<img class="thumb" src="${esc(x.image)}" onerror="this.outerHTML='<div class=placeholder>📰</div>'">`:'<div class="placeholder">📰</div>'}<div class="card-body"><div class="source-row"><span class="source">${esc(x.source)}</span><span class="time">${new Date(x.pubDate).toLocaleDateString()}</span></div><h3>${esc(x.title)}</h3><div class="summary">${esc(x.description||"Latest report from the publisher.")}</div><a class="read" href="${esc(x.link)}" target="_blank">Read full story ↗</a></div></article>`).join(""):'<div class="empty">🔎<h2>No matching stories</h2><p>Try another search or newspaper.</p></div>'}
async function load(){ $("#status").textContent="Updating your news desk…";try{let r=await fetch("/api/news?category="+category);let d=await r.json();items=d.items||[];let names=[...new Set(items.map(x=>x.source))].sort();$("#source").innerHTML='<option value="all">All newspapers</option>'+names.map(x=>`<option>${esc(x)}</option>`).join("");$("#status").textContent="News desk updated • "+new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"});render()}catch{$("#status").textContent="Unable to connect to live news.";$("#newsGrid").innerHTML='<div class="empty">⚠️<h2>News service unavailable</h2></div>'}}
function setCat(c){category=c;document.querySelectorAll("[data-category]").forEach(x=>x.classList.toggle("active",x.dataset.category===c));$("#sectionTitle").textContent=titles[c];load()}
document.querySelectorAll("[data-category]").forEach(x=>x.onclick=()=>setCat(x.dataset.category));$("#search").oninput=render;$("#source").onchange=render;$("#refreshSide").onclick=load;
function recite(){if(!("speechSynthesis"in window))return toast("Text-to-speech is not supported.");speechSynthesis.cancel();if(!items.length)return toast("No news loaded.");let t="Welcome to NewsSphere. Here is your "+category+" briefing. "+items.slice(0,20).map((x,i)=>`News ${i+1}, from ${x.source}. ${x.title}. ${x.description||""}`).join(" ");let u=new SpeechSynthesisUtterance(t);u.rate=.92;u.onstart=()=>toast("🔊 Recitation started");u.onend=()=>toast("Recitation finished");speechSynthesis.speak(u)}
$("#reciteBtn").onclick=recite;$("#reciteSide").onclick=recite;$("#stopRecite").onclick=()=>{speechSynthesis.cancel();toast("Recitation stopped")};
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();prompt=e;$("#installBtn").hidden=false});$("#installBtn").onclick=async()=>{if(prompt){prompt.prompt();await prompt.userChoice;prompt=null;$("#installBtn").hidden=true}};window.addEventListener("appinstalled",()=>toast("NewsSphere installed!"));
$("#themeBtn").onclick=()=>{document.body.style.filter=document.body.style.filter?"":"brightness(.86)";toast("Display mode changed")};
if("serviceWorker"in navigator)navigator.serviceWorker.register("/sw.js");load();